reorder_imports = true
unstable_features = true
indent_style = "Visual"
fn_single_line = true
wrap_comments = true
use_try_shorthand = true
use_field_init_shorthand = true
reorder_imports = true
max_width = 80
