let mapleader=";"
let g:powerline_pycmd="py3"

" yank/paste between vim sessions with a file
" https://vim.fandom.com/wiki/Copy_and_paste_between_Vim_instances
" (For vim's that were not compiled with '+clipboard'
"  -> if ':echo has('clipboard')' returns 0, you need these next lines)
let g:session_yank_file="~/.vim_yank"
map <silent> <Leader>y :call Session_yank()<CR>
vmap <silent> <Leader>y y:call Session_yank()<CR>
vmap <silent> <Leader>Y Y:call Session_yank()<CR>
nmap <silent> <Leader>p :call Session_paste("p")<CR>
nmap <silent> <Leader>P :call Session_paste("P")<CR>

function Session_yank()
  new
  call setline(1,getregtype())
  put
  silent exec 'wq! ' . g:session_yank_file
  exec 'bdelete ' . g:session_yank_file
endfunction

function Session_paste(command)
  silent exec 'sview ' . g:session_yank_file
  let l:opt=getline(1)
  silent 2,$yank
  if (l:opt == 'v')
    call setreg('"', strpart(@",0,strlen(@")-1), l:opt) " strip trailing endline ?
  else
    call setreg('"', @", l:opt)
  endif
  exec 'bdelete ' . g:session_yank_file
  exec 'normal ' . a:command
endfunction

" set some vars
set laststatus=2
set number
set relativenumber
set mouse=a
set showtabline=2
set autoindent
set smartindent
set tabstop=4
set expandtab
set shiftwidth=4
set smarttab
syntax on

" colorcolumn
set colorcolumn=80
highlight ColorColumn ctermbg=0

" tabs
map <Leader>t :tabnew<CR>
map <Leader>q :tabclose<CR>
map <C-PageUp> :tabprevious<CR>
map <C-PageDown> :tabnext<CR>

" windows (panes in tabs)
map <C-J> :wincmd j<CR>
map <C-K> :wincmd k<CR>
map <C-H> :wincmd h<CR>
map <C-L> :wincmd l<CR>

