let mapleader=";"
let g:powerline_pycmd="py3"

" yank/paste between vim sessions with a file
" https://vim.fandom.com/wiki/Copy_and_paste_between_Vim_instances
let g:session_yank_file="~/.vim_yank"
map <silent> <Leader>y :call Session_yank()<CR>
vmap <silent> <Leader>y y:call Session_yank()<CR>
vmap <silent> <Leader>Y Y:call Session_yank()<CR>
nmap <silent> <Leader>p :call Session_paste("p")<CR>
nmap <silent> <Leader>P :call Session_paste("P")<CR>

function Session_yank()
  new
  call setline(1,getregtype())
  put
  silent exec 'wq! ' . g:session_yank_file
  exec 'bdelete ' . g:session_yank_file
endfunction

function Session_paste(command)
  silent exec 'sview ' . g:session_yank_file
  let l:opt=getline(1)
  silent 2,$yank
  if (l:opt == 'v')
    call setreg('"', strpart(@",0,strlen(@")-1), l:opt) " strip trailing endline ?
  else
    call setreg('"', @", l:opt)
  endif
  exec 'bdelete ' . g:session_yank_file
  exec 'normal ' . a:command
endfunction

" set some vars
set laststatus=2
set number
set relativenumber
set mouse=a
set showtabline=2
syntax on

" colorcolumn
set colorcolumn=80
highlight ColorColumn ctermbg=0

" tabs
" note: <C-T> later
map <C-T> :tabnew<CR>
map <C-W> :tabclose<CR>
map <C-H> :tabprevious<CR>
map <C-L> :tabnext<CR>

